version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: next_chapter_api
    volumes:
      - ./database/postgres:/var/lib/postgresql/data

  redis:
    image: redis
    networks:
      - next-chapter-api
    ports:
      - 6379:6379

networks:
  next-chapter-api:
