name: GitHub Actions
run-name: ${{ github.actor }} is running GitHub Actions 🚀
on:
  push:
    branches:
      - main
      - develop
    pull_request:
      - main
      - develop
jobs:
  code_quality_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.10.0]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install
      
      - name: Run CommitLint
        run:  npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

      - name: Format code
        run: yarn format
      
      - name: Build project
        run: yarn build
